### ISSUE TITLE
silent creation of ASE calculator

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEinterfaces#5]
I think it would be preferable not to print `Loading potential: __ase_calc__ = read_dict( load_dict("run_dir/ACE.B_test.json")["IP"])
` by default every time a calculator is created.

**Comment by cortner** [comment]
I think that's this line: 

https://github.com/ACEsuit/ACEinterfaces/blob/25cae7a7eb5297be866a16f77a131fcb16e33060/ase/ace/ace.py#L122

yes, we should create a `verbose` flag for `__init__`

**Comment by bernstei** [comment]
I can make a PR if you give me write permission to the repo (username bernstei)

**Comment by cortner** [comment]
done

**Comment by cortner** [comment]
Closed by #8
